Hometask 1
LuckyMan777/smart-home-2019 pull request #1
Opened 2019-10-11 07:33 UTC by LuckyMan777

2019-10-15 20:28 UTC, a-ivanov commented
Удалите из пулл реквеста ве файлы их директории target. Добавьте ее в .gitignore. Эти файлы не являются исходным кодом проекта.

2019-10-15 20:51 UTC, a-ivanov requested changes

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeProvider.java
> +    SmartHome provideSmartHome() throws IOException, ClassNotFoundException;
Детали имплементации появляются в абстракции (leaky abstraction). Уберите их.

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeProcessing.java
> +        SmartHome smartHome = smartHomeProvider.provideSmartHome();
Почему обработчик событий инициализирует дом? На ком лежит ответственность за инициализацию и сборку зависимостей? Сейчас здесь нарушен SRP. Детали этого нарушения появляются в сигнатуре метода.
Поправьте.

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartDevice.java
> +public class SmartDevice implements SensorEventHandler {
Здесь нарушен SRP. SmartDevice ответственен за состояние объекта дома и одновременно обрабатывает события.
Подсказка: в этом задании нет смысла использовать наследование.
Исправьте.

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartDevice.java
> +    public void handleSensorEvent(SensorEvent sensorEvent, SmartHome smartHome) {
Этот метод не делает ничего. Зачем он тогда нужен?

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public Collection<AdditionalSensorEventHandler> getAdditionalSensorEventHandlers() {
Работайте с данными внутри класса - не создавайте передатчика данных https://martinfowler.com/bliki/TellDontAsk.html. Если эти данные обрабатываются в другом месте, может быть они там и должны быть?

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    Collection<AdditionalSensorEventHandler> additionalSensorEventHandlers;
SmartDevice и AdditionalSensorEventHandler имплементируют один и тот же интерфейс, зачем их разделять в разные коллекции?

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Light.java
> +/*
Не оставляйте за собой закомментированный код - если он не нужен, уберите его из репозитория.

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HomeBuilder.java
> +/*
Удаляйте ненужный код.

2019-10-15 20:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/AdditionalSensorEventHandler.java
> +    public void handleSensorEvent(SensorEvent sensorEvent, SmartHome smartHome) {
Этот метод не делает ничего. Зачем он нужен?

2019-10-17 21:56 UTC, LuckyMan777 commented
Не придумал как пройтись по всем элементам в HallClosingEventProcessor :( 
Наверное, нужно сделать итератор по всем Actionable, который будет проходиться по всем листьям

2019-10-21 22:08 UTC, a-ivanov requested changes
Немного надо доделать.

2019-10-21 22:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/HallClosingEventProcessor.java
> +            /*for (SmartDevice smartDevice : smartHome.getRooms()) {
Это закомментированный код - ваши комментарии или решение задания?

2019-10-21 22:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Door.java
> +            if (action.getCommand() == DOOR_OPEN) {
Не происходит ли здесь дупликации логики? Ведь в *EventProcessor уже определено, как надо менять состояние объекта. Что должно делать Action? Подумайте и исправьте.
То же самое для Light.

2019-10-21 22:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeProcessing.java
> +        sensorEventProcessors.add(new LightEventProcessor());
Этот класс содержит логику цикла обработки событий. Конфигурационный код чаще меняется, он здесь лишний (OCP). Перенесите это к конфигурационному коду.

2019-10-21 22:08 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeJSONProvider.java
> +        String json = null;
По дефолту null.

2019-10-23 21:15 UTC, a-ivanov requested changes
По 2м заданиям - уже хорошо, доделайте по комментариям.

2019-10-23 21:15 UTC, a-ivanov commented on pom.xml
> +            <groupId>org.junit.jupiter</groupId>
А зачем тут столько дублирующих ссылок на артифакт junit-jupiter?

2019-10-23 21:15 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeProcessing.java
> +    private static void sendCommand(SensorCommand command) {
Отдельная responsibility - нарушен SRP, исправьте.

2019-10-23 21:15 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        for (Actionable room : rooms) {
А если будет событие с объектом дом? Оно будет обработано?

2019-10-23 21:15 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/SmartDevice.java
> +        this.className = this.getClass().getName();
Зачем хранить в отдельном поле? Это всегда можно получить из класса.

2019-10-24 20:42 UTC, LuckyMan777 commented on pom.xml
> +            <groupId>org.junit.jupiter</groupId>
@a-ivanov 
Не знаю, не трогал этот файл ¯\(°_o)/¯

2019-10-24 21:13 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/SmartHomeProcessing.java
> +    private static void sendCommand(SensorCommand command) {
@a-ivanov 
Этот метод нигде и не использовался. Просто забыл удалить(

2019-10-24 21:13 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        for (Actionable room : rooms) {
@a-ivanov 
Поправил. Теперь будет. И с комнатой тоже

2019-10-24 21:24 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/devices/SmartDevice.java
> +        this.className = this.getClass().getName();
@a-ivanov 
Это нужно для десериализации. Если не делать это поле, то при десериализации все девайсы будут инстанцироваться как SmartDevice, а не как конкретный объект-наследник (Light или Door).

2019-10-27 18:18 UTC, a-ivanov requested changes
По первому заданию от меня - зачет. По второму - надо доработать, важно полностью уйти от внешней итерации по объектам дома.

2019-10-27 18:18 UTC, a-ivanov commented on pom.xml
> +            <groupId>org.junit.jupiter</groupId>
Оправдание не очень, вы ответственны за все, что происходит в репозитории. Оставьте одну запись с зависимостями и проверьте, что все работает.

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public static void main(String... args) throws IOException, ClassNotFoundException {
`throws IOException, ClassNotFoundException` еще нужно?

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public Collection<SmartDevice> getSmartDevices() {
Задача 2го задания - уйти от привязки к внутренней структуре комнаты и других объектов. Этого метода не должно быть, удалите его и замените его использования на `void execute(Action action)`.

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +public abstract class Action {
Не надо пользоваться абстрактными классами в этой ситуации - существуют функциональные интерфейсы (с одним методом), использование интерфейса - более гибко в сравнении с наследованием класса.

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/SmartDevice.java
> +        this.className = this.getClass().getName();
Ну вот для этого задания это и есть минус - использование одного родительского класса для объектов дома. Мы получаем лишнюю абстракцию с лишними бессмысленными полями, что ухудшает понимание кода и засоряет его, при этом нет никаких сильных плюсов. IMHO надо этот класс можно убрать. Это просто мой взгляд со стороны и на оценку он не повлияет.

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +    public static void sendCommand(SensorCommand command) {
Это метод входит в API этого обработчика? Это еще одна ответственность обработчика? Тогда зачем он публичный?

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      public Collection<Room> getRooms() {
Во 2м задании мы уходим от привязки к структуре дома. Этот метод необходимо убрать и заменить его использование на Actionable.

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +            for (Room room : smartHome.getRooms()) {
Уберите итерацию по комнатам, используйте Actionable.

2019-10-27 18:18 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +            for (Room room : smartHome.getRooms()) {
Уберите итерацию по комнатам. Используйте Actionable.

2019-10-27 20:57 UTC, LuckyMan777 commented on pom.xml
> +            <groupId>org.junit.jupiter</groupId>
@a-ivanov 
Оставил одну, рвботает

2019-10-27 20:58 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    public static void main(String... args) throws IOException, ClassNotFoundException {
@a-ivanov 
Убрал

2019-10-27 20:59 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/Room.java
> +    public Collection<SmartDevice> getSmartDevices() {
@a-ivanov 
Поправил

2019-10-27 20:59 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/Action.java
> +public abstract class Action {
@a-ivanov 
Заменил

2019-10-27 21:00 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +    public static void sendCommand(SensorCommand command) {
@a-ivanov 
Сделал private

2019-10-27 21:00 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      public Collection<Room> getRooms() {
@a-ivanov 
Поправил

2019-10-27 21:00 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +            for (Room room : smartHome.getRooms()) {
@a-ivanov 
Поправил

2019-10-27 21:00 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +            for (Room room : smartHome.getRooms()) {
@a-ivanov 
Поправил

2019-10-30 12:26 UTC, a-ivanov approved these changes

2019-10-30 12:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +    private static void sendCommand(SensorCommand command) {
Вынесите в отдельный класс, это отдельная responsibility.

2019-11-04 20:28 UTC, merged