Hometask 3
LuckyMan777/smart-home-2019 pull request #2
Opened 2019-10-24 22:31 UTC by LuckyMan777

2019-10-30 12:28 UTC, a-ivanov requested changes
Замержите в эту ветку все исправления по 1 и 2 дз.

2019-11-07 11:31 UTC, a-ivanov requested changes

2019-11-07 11:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +        AtomicBoolean isAlarmed = new AtomicBoolean(false);
А зачем тут используется AtomicBoolean? Вы планируете вызывать этот код из нескольких потоков?

2019-11-07 11:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +            if (sensorEvent.getType() == DOOR_CLOSED || sensorEvent.getType() == DOOR_OPEN ||
Здесь нарушен OCP, зачем привязываться к конкретным типам событий? Когда мы будем добавлять новые события, они не будут обрабатываться корректно.

2019-11-07 11:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +                System.out.println("Sending sms");
Что произойдет после отправки смс? По заданию больше не должно происходить никаких обработок и отправок смс.

2019-11-07 11:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +                    System.out.println("Sending sms");
Повторение отправки, можно это выполнить в одном блоке кода?

2019-11-07 11:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/devices/signalizationstates/State.java
> +public abstract class State {
Конкретизируйте, чье это состояние, такое название класса - не очень понятное.
IMHO: зачем делать абстрактный класс, когда это можно легко сделать с помощью интерфейса?

2019-11-12 09:59 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +        AtomicBoolean isAlarmed = new AtomicBoolean(false);
Переделал на final

2019-11-12 09:59 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +            if (sensorEvent.getType() == DOOR_CLOSED || sensorEvent.getType() == DOOR_OPEN ||
Исправил

2019-11-12 09:59 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +                System.out.println("Sending sms");
Исправил

2019-11-12 09:59 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +                    System.out.println("Sending sms");
Исправил

2019-11-12 10:00 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/devices/signalizationstates/State.java
> +public abstract class State {
Думал что название пакета говорит само за себя. Но исправил название

2019-11-12 23:37 UTC, a-ivanov approved these changes

2019-11-12 23:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +        final Signalization[] signalization = new Signalization[1];
А зачем массив из одного элемента?

2019-11-12 23:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +        AtomicBoolean correct = new AtomicBoolean(false);
AtomicBoolean - это для синхронизации потоков, тут это не надо.

2019-11-13 10:00 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventprocessors/SignalizationDecorator.java
> +        final Signalization[] signalization = new Signalization[1];
Переменная, используемая в лямбда выражении, должна быть final или effective final. 
Если бы я сделал signalization final переменной, я бы не смог её менять. Поэтому я сделал массив final. Сам массив я не меняю, а элемент внутри него - меняю.

2019-11-13 10:01 UTC, LuckyMan777 commented on src/main/java/ru/sbt/mipt/oop/eventProcessors/HallClosingEventProcessor.java
> +        AtomicBoolean correct = new AtomicBoolean(false);
Изменил на final

2019-11-13 10:03 UTC, merged